### PR TITLE
use prettier to format docs

### PR DESCRIPTION
**Pull request by bingtsingw**

### CODE REVIEW

**Comment by romeerez** [comment]
Vitepress has a weird structure, so .vitepress/theme and .vitepress/config should be in git and to be formatted, but not the .vitepress/cache and also it writes .vitepress/dist when building.

Could you change .prettierignore to only ignore `.vitepress/cache` and `.vitepress/dist`?

Also, by the way, could you remove the `.vitepress/cache` to .gitignore and remove it from git entirely, it has gotten here accidentally.

**Comment by romeerez** [comment]
And after adding .vitepress/cache to gitignore, I guess prettier will ignore it by looking into gitignore and no need for prettierignore. Not 100% sure

**Comment by bingtsingw** [comment]
> And after adding .vitepress/cache to gitignore, I guess prettier will ignore it by looking into gitignore and no need for prettierignore. Not 100% sure

Prettier do not support reading `.gitignore` by default [see this](https://github.com/prettier/prettier/issues/8506).

**Comment by romeerez** [comment]
Thank you, glad to see -11k and formatting is for better!

**Pull request merged**
